version: "3.7"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data
      - ./postgres/pgconf:/etc/postgresql
      - ./postgres/pglog:/var/log/postgresql
    ports:
    - "5444:5432"
  app:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile
      context: ./app
    volumes:
    - ./app:/app
